---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: backend-http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    nodePort: {{ .Values.service.backend.nodePort }}

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: frontend-http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    nodePort: {{ .Values.service.frontend.nodePort }}

{{- if .Values.redis.enabled }}
---
# Redis Service (ClusterIP for internal use only)
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: redis
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
{{- end }}
