# Default values for retriever.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: show-me-the-stock

replicaCount: 1

image:
  repository: 192.168.0.5:5000/show-me-the-stock
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: LoadBalancer
  port: 8501
